### ISSUE TITLE
The `FinishesHandlingMessageBeforeHandlingNext` middleware should be aware of exceptions

### ISSUE THREAD

**Issue by matthiasnoback** [SimpleBus/MessageBus#13]
When an exception occurs while handling a command, it should set `$this->isHandling` to `false`, otherwise the command bus is locked.

**Comment by matthiasnoback** [comment]
Fixed this in v2.0.1.

**Comment by jgoux** [comment]
Thanks a lot for this one. ;)

**Comment by matthiasnoback** [comment]
@jgoux You're welcome, and thanks for uncovering this problem in the first place!
