### ISSUE TITLE
How to serialize a Message to be published in a message queue?

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/MessageBus#15]
I am using MessageBusMiddleware to send some kind of messages (those that implement interface IsHandledAsynchronously) to an ActiveMQ message queue. I want to store the Message in the queue message body (I am using stomp protocol).

I have also written a Symfony command to susbcribe to messages from that queue.

I need a way to serialize/deserialize the Message in the Stomp message body.

I think I could encode the message in json format. My question is:

Where can I put the logic to get a json view from a Message?

I need this:

````
class UserWasRegisteredEvent implements Message, IsHandledAsynchronously
{
    /**
     * @var integer
     */
    private $userId;

    /**
     * @param integer $userId
     */
    public function __construct($userId)
    {
        $this->userId = $userId;
    }

    /**
     * @return string
     */
    public function getUserId()
    {
        return $this->userId;
    }
}
````

to be converted to this:

````
{
  "type": "Message",
  "class": "UserWasRegisteredEvent ",
  "attributes": {
    "user_id": 5N1J32eZvKYlo2CqJ0wc8p5",
  }
}
````

I suppose I need some metadata fields to hydrate a new Message instance from json  and even some kind of Message factory.

My goal is to pull Messages from queue, create again the Message and publish it in the EventBus, but this time without IsHandledAsynchronously interface (or not?).

Another question, how can avoit the Command/Event to be handled twice? If the Message is published in both the standard bus and the middleware bus. In the Message handler the only info I have is the Message. If I don't want to check the instance interface I have to have two different messages: UserWasRegisteredEvent and UserWasRegisteredAsynEvent .

**Comment by matthiasnoback** [comment]
Thanks for some interesting questions!

You don't need to change the event class/implementing interfaces. Just serialize/deserialize using something like the JMS serializer. 

You only need to configure two command buses, and two event buses. One for the publisher, one for the subscriber. This works pretty well since you can have different middlewares for each of the buses. Basically it's:

Command bus 1: gets an incoming command, checks: should be handled asynchronously? Yes? Serialize it, put it on the queue. No? Let the next middleware handle it.

Command bus 2: gets an incoming command (a deserialized message from ActiveMQ), always lets the normal command handler handle it.

**Comment by matthiasnoback** [comment]
I hope this is clear!

**Comment by josecelano** [comment]
Thanks Matthias. I could not see the wood for the trees :-)

I am working on a sample project and I have both producer and consumer/susbcriber in the same application. As you told me I would not have that problem with two different applications, however there are some scenarios where It could happen that and I would need two command buses in the same application (scenario 2 could be such case).

Scenario 1. Two diferent applications (producer/consumer)
--------------

Sample: App1 (web server) App2 (worker sending emails)
App1
1.- User signs up in the web server
2.- New event is published in the event bus (asynchronuous event interface)
3.- Event is sent to the message queue
App2
1.- Symfony command pulling messages from the queue and injecting events in the event bus
2.- Event handler send the email.

Question (off-topic): could we send a command to the App2 instead of an event?
SignupCommand can create a new SendEmailCommand. 

Scenario 2. Only one application (producer and consumer in the same application)
--------------

Sample1: Symfony Asynchronous EventDispatcher
We want the app events to run in another script execution.
1.- Send the event to the queue.
2.- Symfony command (cronjob) to get events from the queue and publish them in the event bus

More info:
- http://jwage.com/post/30490209661/asynchronous-events-with-php-and-symfony2
- http://developer.happyr.com/real-asynchronous-events-with-symfony2

Sample2: My current sample project.
I want to implement Scenario 1 only with 1 application.

Conclusion
--------------

I suppose the way to implement scenario 2 is your previous reply, is not?
I need to create two different buses. I could use "command_bus" from your symfony-bridge bundle
and create another service this way:

````
    asynchronous_command_bus:
        alias: my_bundle.asynchronous_command_bus

    my_bundle.asynchronous_command_bus:
        class: SimpleBus\Message\Bus\Middleware\MessageBusSupportingMiddleware
        public: false
````

Is that correct or I need to do something else more?

**Comment by matthiasnoback** [comment]
You're on the right path here :) In scenario 2 you would just make a copy command_bus.yml and/or event_bus.yml in your project and prefix everything with "asynchronous" or something. Of course, you should only add the middleware you need.

**Comment by josecelano** [comment]
Thanks Matthias. One more question.

You have told me to use JMS serializer.

I need the Message class name to deserialize the message:

````
$data = <<<EOF
<person>
    <name>foo</name>
    <age>99</age>
    <sportsman>false</sportsman>
</person>
EOF;

$person = $serializer->deserialize($data,'Acme\Person','xml');
````

On the other hand in this post:
http://verraes.net/2014/11/domain-events/

Matthias says it is better to define first the message:

````
{ "eventName": "acme.my_app.StockWasDepleted",
    "payload": {
        "productId": "2028A516-04C0-4D42-81F4-98A42E2B08BC",
        "depletedOn": "2014-11-11",
        "pricePerUnit": { "amount": 500, "currency": "EUR"}
    }
}
````

and then create the new object from the message. For example, in scenario 1 App1 and App2 could use different Message classes. I like that point of view, event if finally I use the same Message class in both apps.

Question:
- How could I serialize/deserialize the object whithout using JMS serializer? It was my initial question but now with new context :-)

I could use an eventName as Matthias does and then map that name to my internal class path (which class should do that: mapping from event name to class name?).

In case I do not want to use standard object serialization but convert the mesage to my message format: where do you think it would be a right place for conversion logic? perhaps extending your Message class? ````Message::toJson()```` and ````Message::from($json)````
or should I have another Message class which represents the message sent over the message queue?

**Comment by josecelano** [comment]
I think I have found the solution to the question where to put convertion logic. I could use JMS serializer with yml config file:
http://jmsyst.com/libs/serializer/master/reference/yml_reference
This way my Message class remains decoupled from serializer.
I suppose I can generate almost all message formats I want from the original Message.

The other question is still open: where to map event names to classes.

**Comment by josecelano** [comment]
I think I could store mapping info in Stomp metadada:

- StompFrame command property (http://php.net/manual/en/class.stompframe.php#stompframe.props.command)
or
- Stomp message custom header. Perhaps something like ````exported-from-class:\path\to\class````

This way I do not need:
- Add any other class to map Stomp messages to my domain Message class.
- Add class path to my domain message in json (or any other) format.

What I do not like is: if I change my Message class path then I could have old messages in the queue with the wrong pahh, then it is a valid solution if I only change Message paths when the queue is empty. And I don't consider this solution valid :-(.

**Comment by josecelano** [comment]
I have almost finished, all works fine but I get this error when I add the second command_bus service:

````
There is no message handler for message "Matthias\User\App\Command\RegisterUserCommand"
````

Here is my second command bus config file:

https://github.com/josecelano/ddd-symfony-sample/blob/master/src/Matthias/Common/App/Infrastructure/CommonBundle/Resources/config/asyn_command_bus.yml

Another question. I do not know how I can add a middleware only to the first command bus to make asyn events go to the queue only in the first command.

**Comment by matthiasnoback** [comment]
Ah, right. The missing piece is: you need to add the compiler passes (see the build() method inside the CommandBusBundle class) to register middleware for the async command bus, as well as the handlers.

**Comment by matthiasnoback** [comment]
By the way, I just saw that currently all namespaces are prefixed with my name. Even though I'm honored ;) it is your project and I think it's best if you use your own name, or some anonymous name.

**Comment by josecelano** [comment]
OK. Thanks. I will try to add that missing piece. I think finally I will create an AsynBus bundle with second command/event buses to execute command handlers and event subscribers asynchronously.
I have founf some bundles which do that but I think this is the cleaner solution I have found until now (fomr the DDD point of view) to dispatch events asyncrousouly with Symfony.

Regarding using your name in namespaces, first I tought to do a DDD sample project only to test simple-bus, that´s why it is your name. Later I thought to use the sample project to test some other concepts I want to test. I think I can keep your name for all code related to simple-bus and create new vendor folder for each new library/concept I want to test. In fact you are the vendor ;-)

**Comment by josecelano** [comment]
Now, everything seems to be working correctly. I have created a new bundle AsynchronousBusBundle:

https://github.com/josecelano/ddd-symfony-sample/tree/master/src/Matthias/Common/App/Infrastructure/AsynchronousBusBundle

This bundle adds new command and event buses for asynchronous messages. You only have to add a marker interface (````IsHandledAsynchronously````) to the message (only tested with events) and the event will be send to the queue by a middleware in the standard bus, then a cronjob (symfony command) will pull that message from the queue and re-inject it in the standard event bus.

I have to remove a lot of duplicate code from that bundle. I suppose I can use all classes inside compiler folder from your simple-bus library.

**Comment by matthiasnoback** [comment]
Excellent work. Yes, you can use the code from the SymfonyBridge. I was also thinking about a way to say "I need another command bus", which should help you prevent copying all that code and configuration...

**Comment by josecelano** [comment]
That would be pretty cool! I suppose probably it is very useful to have one command/event bus per susbcriber/worker. If you have one web server and many specialized worker servers to do asyncronous tasks (resize images, send emails, or  whatever else) I suppose  it´s better to send them only the messages they care about instead of sharing the same command/event bus in the web server app. Of course I can do that internally in my middelware with more than one message queue. I can send all commands to the same asyn-worker-bus but then enqueue them in different queues in the message broker. Then I can only pull messages from one queue in the worker. But I do not know in this is better than having more than one message bus. Conceptually I think that is a responsability for command bus not the middleware but I suppose middelware can also be like a "message broker".

Anyway I think too much messages buses are thus unlikely to be needed, Therefore it is not so much work to create new bundles for each of them.

I think my questions is almost closed :-). It only remains one think I do not like: Message class path is store in the Message Queue message metadata (this case Stomp header), which is very dirty, but I suppose it is not you library responsability. Anyway I think It is very common to need a plain text representation (json, xml,..) of the message so perhaps your library can help with that somehow.

**Comment by matthiasnoback** [comment]
We might have to set up a library which makes serializing the message easier. Still, I think many people will want to do this in many different ways, so I'm not sure if we can make such a thing very generic. I will create an issue about the configuration reuse part.

**Comment by cmodijk** [comment]
This is the solution we are currently implementing it's not finished or tested yet but we are working on that. 
* https://github.com/JCID/RabbitMQSimpleBusBridge/

**Comment by josecelano** [comment]
I see you have used the first option I told to @matthiasnoback , instead of using two buses (for sync and asyn messages) you wrap asyn messages in another special message to use the same bus. I have seen you unpack the original message in te MessageBusMiddleware here:

https://github.com/JCID/RabbitMQSimpleBusBridge/blob/master/src/MessageBus/MessageBusMiddleware.php#L40

I think you have to pass the same message in the next method because, I think, all middlewares have to receive the original message. If you have more than one middleware and your middleware is not the first then problably your real message (unpacked from Asyn messages envelope) could not go throw some middlewares. But I am not sure about that, I have not tested too much the library.

**Comment by cmodijk** [comment]
@josecelano If unpacked the message inside the Consumer and send I to the command_bus than it wil get in an infinite loop. I don's see the problem of unpacking the original message and sending it to the next MiddleWare.

**Comment by josecelano** [comment]
Yes, that's way I use two differents buses (two command buses and two events buses).

Your solution @cmodijk was my first thought, but @matthiasnoback told my to use two buses (see above). The first/standard bus has a midddleware publising messages in the message queue and there is a Symfony command/consumer that pulls messages and inject them in the second bus (asyncronous bus which contains events that came from the queue). This second bus has not any middleware. The main advantage is you do not have to use special events, only your IsHandledAsyn interface.

See my sample:
https://github.com/josecelano/ddd-symfony-sample

I don not know if your solution has any other side effect, perhaps @matthiasnoback could tell us something.

**Comment by matthiasnoback** [comment]
I decided not to choose the `if ($message instanceof ProcessAsynchronouly)` approach. It's not about the message, it's about where your handlers are. In the new libraries (e.g. https://github.com/SimpleBus/Asynchronous, https://github.com/SimpleBus/AsynchronousBundle, https://github.com/SimpleBus/RabbitMQBundle) I decided that events should be handled synchronously as well as asynchronously by a different set of handlers. Commands may be handled asynchronously if they can't be handled synchronously.

**Comment by josecelano** [comment]
It makes sense.

**Comment by matthiasnoback** [comment]
Closing this for now, as I assume the new libraries will suffice :) If not, could you add new issues on the related libraries?

**Comment by josecelano** [comment]
I think it's OK. I have to migrate to your new version. I will add new issues on the related libraries if I found any problem during the migration. Thanks.

**Comment by matthiasnoback** [comment]
@josecelano Thanks, looking forward to your feedback!

**Comment by TrkiSF2** [comment]
I have to say gentlemen, great example of a healthy discussion!
