### ISSUE TITLE
Ability to get all registered commands from a command bus

### ISSUE THREAD

**Issue by jgoux** [SimpleBus/MessageBus#17]
Hello,

it could be interesting to have a method to get all the registered commands.

My concrete example is that I want to expose all my application commands ("GET /api/commands").

Internally, the commandBus just have to get them from its HandlerResolver -> HandlerMap.

Something as simple as : 
```php
$commands = $this->commandBus->getRegisteredCommands();
```

**Comment by matthiasnoback** [comment]
Of course this would require you to use the FQCN-approach for naming messages. Then I'd suggest you to create a compiler pass (just like the `RegisterHandlers` compiler pass), which just loops over all `command_handler` tags and collects the values of their `handles` attribute. What do you think?

**Comment by matthiasnoback** [comment]
This (more or less) will be tackled as part of the profiler PR for Symfony.
