### ISSUE TITLE
How event_bus differs from Event Dispatcher component of Symfony ?

### ISSUE THREAD

**Issue by mseshachalam** [SimpleBus/MessageBus#18]
It seems that 'event_bus' works like Event Disptacher in Symfony(or others) by calling different subscriber methods for an event. How can I specify the order to the subscribers ?

**Comment by matthiasnoback** [comment]
Good question! There is easy way to order event subscribers but it's not
needed anyway: they will all be notified of an event no matter what happens
and they can't influence each other. So they are true observers in that
sense.
Op 16 feb. 2015 15:52 schreef "Seshachalam Malisetti" <
notifications@github.com>:

**Comment by mseshachalam** [comment]
I started following your blog, about Command bus, Hexagonal Architecture. You write good. Symfony dedicated "Command" directory to console commands already. When I want to keep my Simple Bus Commands, it was hard find a directory for them(I keep simple bus commands in "Commands" directory now). My question is not answered yet. How is simple bus event_bus different from Symfony event dispatcher. Can you write a sample Symfony app showing the uses of simple bus ? Or may be a working example of DDD with Symfony ?

**Comment by matthiasnoback** [comment]
Thank you!
The event bus is something entirely different. Look at the documentation of
SimpleBus for an explanation. Event subscribers are really just observers,
they can not "stop propagation" or set return values like regular Symfony
events.

I am already working on a sample application. Don't know yet when it's
finished though...
Op 16 feb. 2015 19:03 schreef "Seshachalam Malisetti" <
notifications@github.com>:

**Comment by mseshachalam** [comment]
Thank you.

**Comment by matthiasnoback** [comment]
You're welcome, thanks for using SimpleBus!
