### ISSUE TITLE
Command validation

### ISSUE THREAD

**Issue by josecelano** [SimpleBus/MessageBus#19]
I want to add command validation inside a Command Handler.

Which option do you prefer?:

````
    public function handle(Message $command)
    {
        $command->validate();
    }
````
or
````
    public function handle(Message $command)
    {
        $this->validator->validate($command);
    }
````
@leopro has used second one becuase he uses Symfony validator service to validate commands:
https://github.com/leopro/trip-planner/blob/master/src/Leopro/TripPlanner/Application/Command/CommandHandler.php

Any suggestion?

I do not like using Symfony validator (even if decoupled using an interface) becuase I think there could be some complex rules which can not be defined.

Have you considered adding validate method to Command interface? I suppose you do not, because people can choose between these two options. What is the best option to add that method to my commands? I think I could implement ````interface Validatable```` and add that interface to my commands.

**Comment by leopro** [comment]
@josecelano usually I only use Symfony validator to validate client input, instead I try to validate invariants (the complex rules) inside the entities. If I got the point.

**Comment by josecelano** [comment]
@leopro I does not mean domain rules but, for example: validation for sum of percentage fields to be 100 (althougth this could be considered a domain validation :-)).

On the other hand I have saw that your Form and Command validation is the same. @mathiasverraes in this post: http://verraes.net/2015/02/form-command-model-validation/ considers Form and Command validation two different layers. I thinks it is not easy sometimes to find the limit between form, command, and domain validation but having these three layers give more fexibility even if you add no validation in any of them in some cases, I think.

**Comment by matthiasnoback** [comment]
Thanks for an excellent question. Some responses:

> I do not like using Symfony validator (even if decoupled using an interface) becuase I think there could be some complex rules which can not be defined.
I'd say everything could be validated, because you can easily add new constraints and constraint validators.

Validating the form would be more or less validating the command itself (whether the command *is* the form data or not). This is always part of the story, since the data inside a command object will be used in all kinds of ways once it's inside your domain model, and then other domain rules (invariants) start to be applied. Also, because time has passed, the command object itself may be valid, but when applied inside the domain, no more. So the best thing to do is to validate what you can either in the UI or using form validation. Then hand the command over to the command bus. Inside the domain model you do all kinds of validations/assertions.

For form validation, just use the Symfony validator, but not inside the command bus, but closer to the user, e.g. inside the (web) controller. For domain validation, you can just use simple assertions.

**Comment by josecelano** [comment]
I have forms whose data are Commands like this:
http://williamdurand.fr/2013/12/16/enforcing-data-encapsulation-with-symfony-forms/
So I map a Form to a Command. If I use Symfony form validation what happens if I want to re-use that command in another place for example a console command?

I think I need form validation but also another command validation. If you think it is better to put validation not inside command handler but before injecting it in the command bus (which seems to be a login option), then I suppose I have to call ````$command->validate ()```` or  ````validator->validate($command)```` in the controller or the console command. I suppose internally I could have a validator implementation using Symfony validator, this way I could define rules only in one place. In fact I suppose I could avoid command validation in controller and use it only in console command or any other place where no web form is used.

**Comment by josecelano** [comment]
@dadamssg is using middlewares for command object validation. See https://github.com/SimpleBus/SymfonyBridge/issues/9

**Comment by dadamssg** [comment]
@josecelano sure do. [Even wrote up a little post explaining why](https://gist.github.com/dadamssg/90d4f3c2151862e68c27). 

You said you didn't like symfony's validator because you had complex rules. You can [define your own custom constraints](http://symfony.com/doc/current/cookbook/validation/custom_constraint.html) that either validate a single field, or the entire class. Symfony's validator will allow you to do whatever complex validation you need to. 

I would not have a `$command->validate()`. Inevitably you're probably going to need an outside service to complete the validation. I feel like injecting that into the command object is a code smell. For example, with a `RegisterUserCommand` you'll probably want to hit the database to check that the email/username isn't already being used. Injecting your user repository into the command object just feels strange.

**Comment by josecelano** [comment]
Thanks @dadamssg . 

Ok. Then I could implement all kind of validation in all layers (presentation, app, domain) using Symfony validation (as a collaborator for my validation services).

Then your response to my issue is the second option, I guess.

But my question has become bigger :-) (really I was the first question)

Where should be a concrete validation? I suppose it depends on what that validation represents.

I have just added a post to the PHPinPHP gruop:
https://groups.google.com/forum/#!topic/dddinphp/Ejp1bKf8Eek
and this is the sample code:
https://gist.github.com/josecelano/ded0a68154376dbec7ac

**Comment by matthiasnoback** [comment]
Closing this for now, to get a better vision on the things that need to be done code-wise.

**Comment by josecelano** [comment]
I have done a sample which uses a CommandValidator class for each command:

https://github.com/blockcypher/php-wallet-sample/blob/master/src/BlockCypher/AppWallet/App/Command/CreateTransactionCommandHandler.php#L78

Btw, I's also a sample of use for SimpleBus library. It's a bitocin wallet.

**Comment by matthiasnoback** [comment]
Validation of commands is about providing user-friendly messages on a per-field basis. Once the command is being handled by the command bus, you left the realm of user-interaction and have entered the domain layer, which is unaware of the clients interacting with it.
Domain objects have their own validation rules, which prevents illegal actions on entities and invalid instantiations of value objects.
Both are separate and can't be combined. 

So in the case of forms populating commands, the validation is just meant to help the user provide reasonable input. Once the command is being processed, any mistake in the command's data should trigger a domain-level exception. This means that you shouldn't *need* to validate your command, you can just start processing it - it will fail anyway.
If a smooth user experience is important (for the web it usually is) then you can use form validation to provide localized, detailed, helpful error messages to the user. If it isn't important (for console commands it usually isn't), then you can skip command validation, and just hand the command to the command bus.

**Comment by josecelano** [comment]
thanks @matthiasnoback I did that way becuase I am trying to implement 3 validation levels as it's explained here: 

http://verraes.net/2015/02/form-command-model-validation/

by @mathiasverraes 

I have form validation here:

https://github.com/blockcypher/php-wallet-sample/blob/master/src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Form/Transaction/CreateTransactionType.php#L59

Do you think I should have to validate the conmmand here in the controller:

https://github.com/blockcypher/php-wallet-sample/blob/master/src/BlockCypher/AppWallet/Infrastructure/AppWalletBundle/Controller/Transaction/Create.php#L95

after validatiing the form but before injenting the command in the command bus?

I have just realized that is waht Matthias V. says: 

>Command validation happens after the form is submitted and before the Command is passed to the model. 

My idea of these three validation levels is:

1.- Form validation: check for valid input types (string, date, number, money).
2.- Command validation: lexical validation: string is a valid UUID, for instance.
3.- Domain validation: semantic validation UUID exist in domain.

Sometimes deciding which level to use it's not clear to me. But I think level two it's useful to avoid duplicate validation. For examaple, if you need to validate the same command regardless of whether it was called by a web controller or by console command (althought it seem you would not validate them for console).

**Comment by matthiasnoback** [comment]
If the command is populated by the form component and validated based on some validation constraints (using annotations or something), you don't need to validate the command again. You just let domain-level validations (invariant protection) do their work. A console command doesn't usually need any user-friendly invalidation. If it does, you can still use the validator service to validate the command, as if it were populated by a form. After all, that's just the same thing really.
