### ISSUE TITLE
Possibility to subscribe to multiple events

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/MessageBus#23]
At the moment, the Subscriber only allows you to subscribe to 1 event. It would be really useful if I could write 1 subscriber that subscribers to multiple events for logging purposes etc...

**Comment by matthiasnoback** [comment]
I'm not sure if I get what you mean - using service tags (if you use the SymfonyBridge) you can already do this, just add more tags with the same name but different values for "subscribes_to".

**Comment by ruudk** [comment]
I see, but there is no way to map the different Events to different `notify` methods?

So for example:

```php
// RefundCreatedEvent
public function notifyRefundCreatedEvent(Message $message);

// RefundPaidEvent
public function notifyRefundPaidEvent(Message $message);
```

**Comment by matthiasnoback** [comment]
Ah, hehe, no, sorry about that. There is just one method for all events in that case, maybe you could some "ugly" switch statement there? Or add methods on the event themselves to differentiate the way you want to treat them.

**Comment by ruudk** [comment]
I see... Maybe it's a good thing to just keep this lib simple as possible :)

I'll leave them in separated subscribers then. Thanks!

**Comment by matthiasnoback** [comment]
Also, sometimes middleware can be a solution for this type of problem.
Op 21 apr. 2015 20:32 schreef "Ruud Kamphuis" <notifications@github.com>:
