### ISSUE TITLE
Too many interfaces?

### ISSUE THREAD

**Issue by acasademont** [SimpleBus/MessageBus#24]
Hi Matthias!

I'd first like to thank you for this nice library, it's very well done!

However, we feel that there are too much mandatory interfaces to comply with, and that couples our commands and command handlers to your implementation. Let me show that with an example. This is a Command and a Command Handler example, we wrote this classes before choosing a command bus implementation (maybe we would write our own)

```php
final class SignUpUser
{
    private $email;
    
    public function __construct($email)
    {
        $this->email = $email;
    }
    
    public function email()
    {
        return $this->email;
    }
}

final class SignUpUserHandler
{
    private $userRepository;
    
    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }
    
    public function handle(SignUpUser $command)
    {
        $user = new User($command->email());
        
        $this->userRepository->register($user);
    }
}
```

Now we go on the quest to find a command bus implementation that is nice and provides fancy middleware (Doctrine) and integrates with Symfony. We find yours which seems nice but unfortunately we have to implement some interfaces that force us to modify example.

```php
final class SignUpUser implements Command
{
    private $email;

    public function __construct($email)
    {
        $this->email = $email;
    }

    public function email()
    {
        return $this->email;
    }
}

final class SignUpUserHandler implements MessageHandler
{
    private $userRepository;

    public function __construct(UserRepository $userRepository)
    {
        $this->userRepository = $userRepository;
    }

    public function handle(Message $message)
    {
        $user = new User($message->email());

        $this->userRepository->register($user);
    }
}
```

As you can see we are now tightly coupled to the command bus implementation and we have lost valuable expressiveness having to type hint on `Message` instead of our `SignUpUser`.

So my question is: why are these interfaces needed? If we agree that we are going to pass something (a Command) to some class (a Command Handler) that has the `handle` method we can get rid of the interfaces and everything just works with less coupling. Tactician works like this and I feel that it's a better approach (well, they have an Inflector service if you don't want the method in your Command Handlers be called `handle`, but no interfaces in the Commands nor Command Handlers) even I prefear the combined Event/Command approach of this package.

Thanks!!

**Comment by jenkoian** [comment]
This is essentially what I was getting at with https://github.com/SimpleBus/CommandBus/pull/2 :)

Also, for reference here is the discussion around this on tactician: https://github.com/thephpleague/tactician/issues/43

**Comment by acasademont** [comment]
Ah! I should have checked the closed issues too, thanks ;)

**Comment by acasademont** [comment]
That was in the old CommandBus repo, that's why I didn't find the issue before. Well, hope @matthiasnoback can reconsiderate this in light of the Tactician discussion :)

**Comment by matthiasnoback** [comment]
I actually discussed this with @rosstuck yesterday and I totally agree. In fact, I'm already testing this approach for a new major release of SimpleBus/MessageBus.

**Comment by acasademont** [comment]
That would be awesome! It would be great if you could open a branch to test and give feedback

**Comment by matthiasnoback** [comment]
I will do that soon.

**Comment by tomaszhanc** [comment]
Also, can't wait for that! :)

**Comment by matthiasnoback** [comment]
Good to know you're awaiting these changes!

I'm working in the `decoupling` branch right now: https://github.com/SimpleBus/MessageBus/tree/decoupling There are some things that I'd like to tackle first, but this will be a new major version and that means quite some changes to the other libraries as well. So you may have to wait for a bit longer ;)

**Comment by ruudk** [comment]
@matthiasnoback Looks great! Would it be an option to make the `handle`/`notify` methods configurable too? That way I can have 1 subscriber that listens to multiple different events, something like:

```php
class LogSubscriber
{
    public function notifyUserCreated($event);
    public function notifyUserUpdated($event);
    public function notifyUserDeleted($event);
}
```

```xml
<service id="user_subscriber" class="UserSubscriber">
  <tag name="event_subscriber" subscribes_to="UserCreatedEvent" method="notifyUserCreated" />
  <tag name="event_subscriber" subscribes_to="UserUpdatedEvent" method="notifyUserUpdated" />
  <tag name="event_subscriber" subscribes_to="UserDeletedEvent" method="notifyUserDeleted" />
</service>
```

**Comment by matthiasnoback** [comment]
@ruudk I had your request in mind when I was working on this ;) And yes, what you describe is already the case in this library. The next step will be to update the SymfonyBridge to reflect these changes.

**Comment by acasademont** [comment]
Looks great, I would say it's even simpler now :)

**Comment by matthiasnoback** [comment]
@acasademont True, much simpler, I'm happy that this is changing now.

**Comment by acasademont** [comment]
My only suggestion would be that if no method name is provided in the callable map a default name `handle` is used so the handlers array stays BC, one less thing to change from 2.0 to 3.0.

```php
$commandHandlersByCommandName = [
    'Fully\Qualified\Class\Name\Of\Command' => 'command_handler_service_id'
];
```

would call the method `handle` on the given service

If you want full customization of the handler method you can use the new syntax

```php
$commandHandlersByCommandName = [
    'Fully\Qualified\Class\Name\Of\Command' => ['command_handler_service_id', 'anotherMethodName']
];
```

**Comment by ruudk** [comment]
@acasademont :+1:

**Comment by matthiasnoback** [comment]
Yes, I was considering that, but I still like to remove the interface in that case - So I could just add an extra case like `if (method_exists($callable, 'handle')) { return [$callable, 'handle']; }`

**Comment by acasademont** [comment]
Yeah, that would be great

**Comment by matthiasnoback** [comment]
Cool, I will add it.

**Comment by matthiasnoback** [comment]
Hi all, as you may have seen already, this has been fixed in the new major release of the SimpleBus packages :) Handlers/subscribers can be any callable now. No need to implement the interfaces (which have been removed by the way ;)).

**Comment by tomaszhanc** [comment]
Thank you very much! I'm going to test this now. :)
