### ISSUE TITLE
Warn users when they record events inside a Subscriber

### ISSUE THREAD

**Issue by ruudk** [SimpleBus/MessageBus#26]
As the Subscriber middleware doesn't check the `public_event_recorder` for new Messages we should probably warn users when they record messages during execution of a subscriber.

**Comment by jeremyb** [comment]
Hello @ruudk,

I had the same issue on my project, something like a command that record an event in the `PublicMessageRecorder` and the related subscriber also record an event that is never executed. Is it also your issue?

I fixed it by overwritting the `HandlesRecordedMessagesMiddleware` and updating the following lines https://github.com/SimpleBus/MessageBus/blob/master/src/Recorder/HandlesRecordedMessagesMiddleware.php#L37-L43 by:

```php
while ($recordedMessages = $this->messageRecorder->recordedMessages()) {
    $this->messageRecorder->eraseMessages();

    foreach ($recordedMessages as $recordedMessage) {
        $this->messageBus->handle($recordedMessage);
    }
}
```

It fixes my issue and handle all my subscribers in cascade.
I can make a PR if you want @matthiasnoback (BTW thanks for this cool lib :)).

**Comment by matthiasnoback** [comment]
Interesting thing you're talking about here. To make it really consistent I guess we should pass along any recorded event to the event bus after handling event subscribers as well. It's a valid use case after all. My assumption was that only command handlers produce events, but this isn't necessarily so... Wouldn't it be as simple as reusing the same middleware class and register it as event bus middleware?

**Comment by ruudk** [comment]
I don't know. Is it really O.K. for a Subscriber to record events? Maybe it should be discouraged? I think that a Subscriber should only pass new commands to the Commandbus?

**Comment by matthiasnoback** [comment]
I agree, but preventing the user from recording events in an event subscriber is impossible (because it would require information about the context). So maybe it would be sufficient just to document this, what do you think?

**Comment by ruudk** [comment]
Sure, that would be fine.

**Comment by Shivella** [comment]
Same issue here, Throwing exception should have saved me lot of time.

**Comment by matthiasnoback** [comment]
Hmm, I still wouldn't like to throw exceptions in the message recorder, since that would force us to add context to it (it shouldn't know when or why it's asked to record a message, right?). If you want to process new events generated while handling previous events, you could just append the middleware which collects and handles recorded messages. I think that should be a suggestion in the docs as well.

**Comment by matthiasnoback** [comment]
Anyone like to write something for the docs?

**Comment by ruudk** [comment]
Wouldn't it be better to just append the `HandlesRecordedMessagesMiddleware` to the `event_bus` by default?

**Comment by matthiasnoback** [comment]
Could be, yes. Then nobody would be disappointed that they aren't sent right? That would be something for the SymfonyBridge though. It should also be tested to see if there are no recursion issues (either in the code or in the service definitions).

**Comment by matthiasnoback** [comment]
To conclude this, I added a note about this to the documentation.
Recording events is something that was specifically invented for command handling (to record them first, then handle them only after the db transaction was successfully committed). If an event subscriber generates a new event, then you can just let the event bus handle it right there.
