### ISSUE TITLE
Question: Composition of commands

### ISSUE THREAD

**Issue by lars-feyerabend** [SimpleBus/MessageBus#27]
Hi there,

in a larger Symfony project I'm currently working on we're using MessageBus as an intermediate layer for write actions (changing something, creating something, deleting something). We do this to avoid monolithic manager classes that bundle too much functionality and dependencies and have task-specific handlers with only the necessary dependencies. (Also it allows us to implement logging and access control, etc. as a central middleware.)

That being said, I find it difficult to grasp how commands can work together. For example, I have a command that can store an uploaded image file to our asset library (`StoreAssetCommand`). Now let's say I have another command that creates, for example, a Car entity. A car can have a picture, i.e. a linked asset. Generally, we use command objects as `data_class` for our UI forms, so we would have a `CreateCarCommand`, with member variables `make`, `model`, and `picture`, which get filled through a CreateCarType with fields `make` (`text`), `model` (`text`), `picture` (`file`).

Conceptually, I like this approach. By filling the form, you essentially fill in a CreateCar "request", that can be validated and eventually executed, resulting in a newly created car.

But how would I integrate the already existing `StoreAssetCommand`? The steps to take would be similar to this:

```php
public function __invoke($message) {
  $car = new Car();
  $car->setMake($message->getMake());
  $car->setModel($message->getModel());
  
  $picture = magicWayToCreateANewAsset($message->getUploadedFile());
  $car->setPicture($picture);
  $this->em->persist($car);
}
```

How would I use my `StoreAssetCommand` as `magicWayToCreateANewAsset`? I can't just create it and put it on the command bus from within my `CreateCarCommandHandler`, because a) the `CreateCar` command would finish first, and b) there's no way to get the newly created `Asset` object back to the `$car` object (commands have no return path).

My current solution is to externalize the asset creation to an `AssetManager` and have the `StoreAssetCommand` just call the manager. But I don't like the solution: the command handler only adds a very thin layer on top of manager methods, and I end up with big manager classed I wanted to avoid in the first place...

Any ideas on how to approach this? What's a cleaner solution to this? (Feel free to question the problem scenario, as well.)

Thanks for reading,
Lars

**Comment by lars-feyerabend** [comment]
I just discussed this with a colleague.

Would it solve my problem if commands were `Deferred` and still be consistent with the `MessageBus` concept?

I imagine it like so:

```php
public function __invoke($message) {
  $car = new Car();
  $car->setMake($message->getMake());
  $car->setModel($message->getModel());
  $this->em->persist($car);

  $subCommand = new StoreAssetCommand($message->getUploadedFile());
  $promise = $subCommand->promise();
  $promise->done(function($picture) use ($car) { $car->setPicture($picture); });
  $this->commandBus->handle($subCommand);
}
```

But I have no clue yet how a PromiseAwareMiddleware for the MessageBus could work and when to resolve promises with what.

**Comment by ruudk** [comment]
What if you just generate the path to the image up-front? That's the way I solved the exact same problem. 

* Create Car entity
* Generate unique path where the file should be stored
* Save if to the Car entity
* Persist
* Fire off the upload command, hoping that it succeeds ;)

The only problem with this approach is that if the upload command fails, you have an entity in a weird broken state.

Maybe it would be an idea to create a special message that can wrap multiple commands inside 1 transaction? So that if 1 of them fails, everything will fail.

**Comment by matthiasnoback** [comment]
Hmm... It feels like the low-level details of handling file uploads belong to the infrastructure layer of the application, whereas the other things you describe are part of the domain model. I think it would be better to handle the file upload (i.e. process the information in `$_FILES`) before you handle the command. The command message then contains the path of the file after it was moved to the right location. Or the command message still contains the path of the temporary location of the uploaded file. You then move the file to the right location inside the command handler. In that case, without having multiple commands, everything fails or succeeds together.

**Comment by matthiasnoback** [comment]
Closing this now, since it's not something that needs fixing :)
