### ISSUE TITLE
PrivateMessageRecorderCapabilities protected record method

### ISSUE THREAD

**Issue by lorenzomar** [SimpleBus/MessageBus#29]
PrivateMessageRecorderCapabilities should have public "record" method to be compatible with RecordsMessages interface.

**Comment by matthiasnoback** [comment]
Well, actually ;) you shouldn't use the trait for instances of
`RecordsMessages` but only for instances of `ContainsRecordedMessages`. If
you want to publicly record messages, there is a class for that already.
With Symfony you can inject the `event_recorder` service.
Op 5 jun. 2015 20:54 schreef "Lorenzo" <notifications@github.com>:
