### ISSUE TITLE
Use result of a CommandHandler->handle()

### ISSUE THREAD

**Issue by holtkamp** [SimpleBus/MessageBus#47]
Since we already use SimpleBus\EventBus, I am currently trying to replace our [Tactician CommandBus](http://tactician.thephpleague.com) with SimpleBus\CommandBus. 

In the Tactician CommandBus, the CommandHandlers [can return a result](https://github.com/thephpleague/tactician/blob/d0f19660f44cc61297a80b269f9554336796a189/src/Handler/CommandHandlerMiddleware.php#L71), which we use like:

```php
$command = new RemoveOrderLineFromOrderCommand($orderLineUuid);
$order = $commandBus->handle($command); // We can return an Order object here
$this->updateFrontEndUsingOrder($order);
```

Now it seems that in the SimpleBus\CommandBus approach [this is not possible / void is returned](https://github.com/SimpleBus/MessageBus/blob/1db0585ca8c2b57d5c1ea17caf4ad2e38250fc73/src/Bus/Middleware/MessageBusMiddleware.php#L13), causing something like:

```php
$orderLine = $orderLineRepository->find($orderLineUuid);
$command = new RemoveOrderLineFromOrderCommand($orderLineUuid);
$order = $orderLine->getOrder(); // The link between OrderLine and Order will be removed, acquire Order
$commandBus->handle($command); // We can not return anything
$this->updateFrontEndUsingOrder($order);
```

Thinking about this, it seems plausible that the handler returns ```void```, since it is possible the Command is handled asynchronously, but just wondering whether this is an 'on-purpose' design decision? Is there a best practice on how to deal with this 'send command and forget' approach? I actually do not want to lookup an Entity at this stage already...

**Comment by matthiasnoback** [comment]
Hi @holtkamp! Thanks for asking this question. If you dig into the issue archive I'm sure this point will be discussed in more detail. It is indeed an on purpose design decision. The trick is usually to make the commands contain merely plain data (like, scalar values and simple arrays), and do all the fetching and modifying inside the command handler.

**Comment by holtkamp** [comment]
Thanks for the response! Mmm, I scanned all issue titles in https://github.com/SimpleBus/MessageBus/issues but could not find anything about the topic of *returning values* by Handlers, you got a pointer? Closing issue anyhow, but I hope you understood the question, it is not about what goes *into* the Command, but what comes *out* of the handlers :wink:

**Comment by matthiasnoback** [comment]
Hmm, sorry about pointing you in the wrong direction. I'm sure I've answered this question many times more.
You can either fetch an entity/view model like you do in the example, or add something like a `Location` header to the response, to tell the client to look for the "result" elsewhere.
