### ISSUE TITLE
CouldNotResolveCallable

### ISSUE THREAD

**Issue by guyradford** [SimpleBus/MessageBus#49]
PHP just dies is an exception is thrown whilst throwing an exception. I use the service locator in ServiceLocatorAwareCallableResolver to instance the event handling class, this sets the first entry in $maybeCalledable to an object. If the method does not exists in the class the resolver tried to throw a CouldNotResolveCallable exception as expected. However since the first item is an object the printValue method fail.

To fix this I updated the printValue method:

```php
private static function printValue($value)
    {
        if (is_array($value))
            array_walk($value, function(&$value){
                if (is_object($value))
                    $value = get_class($value);
            });

        $str = str_replace('  ', '', str_replace("\n", '', print_r($value, true)));
        return $str;
    } 
```

I hope this helps.
Guy

**Comment by matthiasnoback** [comment]
Sorry for the delay. I tried to reproduce this, but can't find any problems. I had added test cases for this (https://github.com/SimpleBus/MessageBus/blob/master/tests/CallableResolver/ServiceLocatorAwareCallableResolverTest.php#L9), and they don't seem to cover a different case than your's. Could you produce a failing test case for your problem please?

**Comment by crazylime** [comment]
Not a problem. Ok I will try to write some tests, it wont be immediately as I am busy at the mo. Thank you for your feedback.

**Comment by fatganz** [comment]
I also can confirm the issue. Sorry, no test yet.

**Comment by cmodijk** [comment]
I think this is because you use print_r here and then the handler has a lot of dependencies like the symfony2 container the print_r wil run out of memory if there is a lot of services initialized. Inside the tests the handler is a very simple one so that won't just 'die'. I have added an example of recursive error [here](https://github.com/cmodijk/MessageBus/commit/0a70acc5d80eb8cc275f358452296a1267c934be) as you can see the `childHandler` child service is also inside the message and with a lot of or big dependencies this can create memory problems.

**Comment by fatganz** [comment]
Yes, my issue was also related to Symfony. @cmodijk thanks for the test.

**Comment by fatganz** [comment]
@matthiasnoback can you please check this, as this causes a lot of pain for Symfony users who often are making typos in configs )).

P.S. Thanks for great library!

**Comment by matthiasnoback** [comment]
Hi, sorry, I don't have a lot of open-source time these days... Could anyone of you propose a fix? It can be quite simple I guess and then I can just merge it.

**Comment by cmodijk** [comment]
Done, just created a pull request #50

**Comment by guyradford** [comment]
Thank you @cmodijk  for doing the pull.

**Comment by cmodijk** [comment]
@guyradford No problem :)

**Comment by cmodijk** [comment]
@guyradford Could you try the 2.2.2 version? @matthiasnoback Released the new version with my pull request.

**Comment by matthiasnoback** [comment]
Right, I forgot to mention it in this thread. Please let us know if your
problem has been fixed.

**Comment by cmodijk** [comment]
@guyradford Did you already tried the new version?

**Comment by guyradford** [comment]
@cmodijk just done a composer update... we haven't hit this bit of code since we started the project. Ill report if we see any issues.
