### ISSUE TITLE
declare name() static

### ISSUE THREAD

**Issue by farconada** [SimpleBus/MessageBus#5]
name() method of events and commads could be static. The name of the event/command it handles is not part of the state of the object, it's something like a tag for this class. Using the name() as an instance method is problematic if you use the commands inside twig forms

**Comment by matthiasnoback** [comment]
I agree that `name()` may interfere with existing properties. But so might methods like `occurredOn()`, etc. Constants are no option for me because you can't make them a mandatory part of the interface. We might rename the method to `messageName()` to prevent naming conflicts - what do you think?

**Comment by farconada** [comment]
Better messageName() than name() but even better if:
```
  interface Event {
    public static messageName();
  }
```
It's ok since PHP 5.3, so it's no problem 
http://php.net/manual/es/language.oop5.interfaces.php#96137

**Comment by matthiasnoback** [comment]
That's right. I must think about this, I'm not sure if making the method static really helps. However, messageName() is better at least to avoid collisions.

**Comment by farconada** [comment]
just tested:
public static function messageName();
works but
public static function name() 
doesnt work cause also Symfony form also calls statics methods.
so messageName() o even _messageName() are right names

**Comment by matthiasnoback** [comment]
I will probably go for `public static function messageName()`. The name of a message can not be different per message instance.

Still, I would like to know what your specific problems with Symfony forms are. Do you have some sample code of what you are trying to achieve and in which way this library stands in the way?

**Comment by farconada** [comment]
$command = new DummyCommand();
        $command->name = 'The command itself';
        $command->content = 'The content itself';
        $form = $this->createForm(new DummyType(), $command);

if name() or static name() the form displays:  "dummy_command" else "The command itself"

**Comment by matthiasnoback** [comment]
Ah! I see. So we are indeed fighting naming collisions. A command/event is less likely to contain the property "messageName", so renaming the method would solve that issue.

Also, I will make it static because the name applies to all instances of the message.

**Comment by farconada** [comment]
:+1:

**Comment by matthiasnoback** [comment]
Cool, doing it now :)
