### ISSUE TITLE
Broken link on getting started

### ISSUE THREAD

**Issue by alexlongshaw** [SimpleBus/MessageBus#51]
The event bus link in the body of [getting started](http://simplebus.github.io/MessageBus/doc/getting_started.html) should have the extension .html rather than .md.

It changed from .html to .md during this commit: https://github.com/SimpleBus/MessageBus/commit/20a66fe61e6d8a7cdfcf1391fd6dc212cab86673

It appears to be due to a bug in coucous: https://github.com/CouscousPHP/Couscous/issues/112. Regenerating with the latest version of couscous fixed the issue for me.

**Comment by matthiasnoback** [comment]
Thanks for this! I'll run the build again some time.

**Comment by matthiasnoback** [comment]
Okay, finally got around to doing this. Thanks again!
