### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Nyholm** [SimpleBus/MessageBus#57]
I find the documentation for the simplebus project hard to navigate and understand. It is great that all the libraries/bundles are small and focused but the documentation should not be the same. 

I was thinking to gather all of in in one repo and add an index page and group the content in topics.

What do you think about that? Im happy to make a first draft if you like the idea.

**Comment by cmodijk** [comment]
@Nyholm Tnx for the response my idea is that the documentation for the specifiek part should be part of the different libraries. The reason for me to choose this approach is that it is easier to add documentation with your pull requests of new features. 

I do agree hover that the documentation is hard to navigate and understand and i wish we could create a second repository which includes some more documentation with for instance cookbooks on how to do things and that we read al the different repositories for specifiek integrations. 

What do you think about that approach?

**Comment by Nyholm** [comment]
Hm. Do you mean that we should automatically sync docs from the repos to the doc page? That sounds nice but might be too complicated. 

I'm at Symfony con at the moment. I talked around with a bunch of developers here, both about simplebus and about docs in general. The common expectation is that all repos have very technical and short docs about features and then you have a separate repo with "how to get started", overview, cookbook, and "human readable" docs about each component. 

If you create a documentation repo and give me push access I will be happy to make a first suggestion.

**Comment by cmodijk** [comment]
For every one interested in this we are in de proces to migrate the docs to http://docs.simplebus.io/ the repository for this can be found here https://github.com/SimpleBus/docs it still a work in progress so if you have any feedback or changes please submit a pull request or create an issue there.

**Comment by cmodijk** [comment]
I'm closing this. We have the new repo and there are al the issues related to finish the transition.
