### ISSUE TITLE
How to pass events to event bus using the DoctrineORMBridge

### ISSUE THREAD

**Issue by webdevilopers** [SimpleBus/MessageBus#59]
It took me some time to answer my own question I asked here:
* https://github.com/webdevilopers/php-ddd/issues/21#issuecomment-266717263

Finally I've got everything working. Since I use the `DoctrineORMBridge` I realized that the events are correctly only handled after Doctrine persisted the involved `Entity` / `DomainModel`.

I just wonder if the following step is really necessary:
```php
        foreach ($foo->recordedMessages() as $event) {
            $this->eventBus->handle($event);
        }
        $this->modelRepository->save($foo); // persist and flush
```

Or if this can be done automatically somehow?

**Comment by cmodijk** [comment]
@webdevilopers Well this is being done by the `DoctrineORMBridge` but the think is the events are only triggert when you dispatch the save method from a command handler. There are seral things that are still pending. 

* This is a pull request made to handle events that have been collected and to dispatch them from outside of the command handler.
    * https://github.com/SimpleBus/MessageBus/pull/42
* The second is this open pull request to switch the collection to a different method. 
    * https://github.com/SimpleBus/DoctrineORMBridge/pull/4

The reason why the doctrine bundle does not dispatches the events itself is that when you call `persist` and `flush` inside a command handler you may have some more work to do before you are done. So they get recored and when the command handler is done they get executed and your command can't fail on the even listeners if they trow a `Exception`.

**Comment by cmodijk** [comment]
I'm closing this as https://github.com/SimpleBus/DoctrineORMBridge/pull/4 is very close to get merged. This solves the problem of not dirty entities to trigger the events. The handeling outside a command is still not a recommend way of changing entities.
