### ISSUE TITLE
How to map command to handler with conventions rather than explicit map?

### ISSUE THREAD

**Issue by lezhnev74** [SimpleBus/MessageBus#60]
Hi!
I've just started to learn SimpleBus internals and I am wondering if I can make Bus resolve handler by simply knowing the Command name (FQCN)?

So having `\App\CommandA\CommandA` class, it will find handler in `\App\CommandA\CommandAHandler`?

Does it look like a decent practice to you?

**Comment by matthiasnoback** [comment]
The problem is not about resolving the handler to `{name of command}Handler` (that would in fact be doable), it's more about how to create an object based on that class name. Hence, the translation to a service identifier first, so you can let the service container instantiate the handler, including all its required constructor arguments.

**Comment by cmodijk** [comment]
@lezhnev74 @matthiasnoback is correct in the fact that the system does not know how to create an instance of that class. But you are maybe interested in the autowiring feature which is being developed right now. 
* https://github.com/SimpleBus/SymfonyBridge/pull/40

**Comment by lezhnev74** [comment]
@cmodijk sure, I understand that instantiation of the CommandHandler must be directed by some sort of `ServiceLocator`.

But before we can resolve the handler through the dependency container, we need to figure out the name to resolve. 

There is an example in documentation:
```php
use SimpleBus\Message\CallableResolver\CallableMap;
use SimpleBus\Message\CallableResolver\ServiceLocatorAwareCallableResolver;

// Provide a map of command names to callables. You can provide actual callables, or lazy-loading ones.
$commandHandlersByCommandName = [
    'Fully\Qualified\Class\Name\Of\Command' => ... // a "callable"
];
```

As it implies I have to map commands to particular handlers. What I want is skip this configuration step and use a convention that command handler has the same FQCN as command + `Handler` at the end.

By this convention, I could simplify the code structure and maintainability.

**Comment by lezhnev74** [comment]
Recently I've been playing with getprooph.org. It uses event based architecture, and it allows injecting my own logic in there without touching the source code. 

Since this issues may look like "power user case", Simple Bus may not have it and I should stick with proophessor.
