### ISSUE TITLE
please document some scenarios the lib try to solve

### ISSUE THREAD

**Issue by videni** [SimpleBus/MessageBus#65]
Hi,  it seems this lib is very interesting but the document doesn't show what case it try to  solve, can you document some scenarios please? for beginner,  understanding the situation the lib can be used is more important than how it solved .

**Comment by cmodijk** [comment]
@videni Tnx we are working on a new documentation on http://docs.simplebus.io/ and https://github.com/SimpleBus/Docs to improve the documentation.

**Comment by videni** [comment]
Thank you
