### ISSUE TITLE
Question About Command Handler Return.

### ISSUE THREAD

**Issue by cydrickn** [SimpleBus/MessageBus#69]
Hi,

I'm just new in design patter of CQRS.
Now while reading articles about this pattern.
It says that the command handler must not return data.
In this case how i will pass the generate data from command handler to controller.
I found articles that they use GUID that was generated before it will pass to command.
But in my case since I'm using Auto-increment in database, how i will know the generated ID.

Thanks.

**Comment by cmodijk** [comment]
@cydrickn Tnx for taking the time to write your comment. But it is indeed the case that you can't return anything inside the handler. The reason behind this is that the command bus should be able to handle the command on a later moment. If you think about in that case it wil not happen at that direct point in time and you will not be able to retrieve the `Auto-increment` as it is not created yet.

I know it is a mind shift and to be honest I had to work on it for a while to wrap my mind around the concept. If you really need a identification of what you are about to create the only way is to start using a UUID and send that with the command to the handler. In our case we implemented both a `Auto-increment` and we are using a `UUID` for cases where we really need to have that reference. 

* https://github.com/SimpleBus/MessageBus/issues/47

**Comment by cydrickn** [comment]
Thanks for the reply @cmodijk,
I will start using UUID now so that i can easily reference my entity.
