### ISSUE TITLE
Functionality to invoke after all messages have been processed

### ISSUE THREAD

**Issue by holtkamp** [SimpleBus/MessageBus#70]
I am trying to come up with functionality that is invoked when all messages on a CommandBus / EventBus have been processed. 

At first I was thinking of creating a middleware for this, but it seems impossible to determine whether a message that is being handled is "the last one". 

@matthiasnoback any suggestions on how to do this?

**Comment by matthiasnoback** [comment]
I don't know a simple way to do that, but you could always simply replace
one "official" middleware with your own and add a way to hook into the
"queue of messages is empty" event.

**Comment by holtkamp** [comment]
Thanks for the swift response!

>you could always simply replace one "official" middleware with your own and add a way to hook into the "queue of messages is empty" event.

mm, that suggested "queue of messages is empty" event would by a userland code event right? Or is it part of the library?

I currently adopted a middleware class and used it at the end of the invoked middleware. "Problem" / challenge is that it will be invoked for all messages/events, which is not very elegant...

**Comment by matthiasnoback** [comment]
Yes, it'll be a userland event. The middleware to replace should be
https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/FinishesHandlingMessageBeforeHandlingNext.php
(I think :))

**Comment by holtkamp** [comment]
Yeah, I had a look at https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/FinishesHandlingMessageBeforeHandlingNext.php already. But that approach seems to deal with "nested" messages. 

- message I
  - message II
    - message N

While I am looking at something like

- message I
- message II
- message N
- at last: do some stuff

I guess this is not possible without changing [the SimpleBus](https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/MessageBusSupportingMiddleware.php) itself. Next to middlewares that deal with the messages, it could/should have the possibility to register callbacks that are invoked *after* the messages are processed: something like `$postProcessCallbacks`. Would you be open to such an addition? Or would you like to keep it simple and keep this "exotic" request in userland code? 😄  Then I will probably extend `MessageBusSupportingMiddleware` and add the functionality there.

**Comment by matthiasnoback** [comment]
I wouldn't go that way. Instead, after the queue is empty, run the "shutdown function". To be clear: you don't use the built-in `FinishesHandlingMessageBeforeHandlingNext` but replace it with your own implementation.

Of course, you could create a PR for this, but I'll leave it to @cmodijk to decide if it enters the project :)

**Comment by holtkamp** [comment]
Thanks for spending your brain time on this 😃 

> Instead, after the queue is empty, run the "shutdown function"

The problem / challenge is that *that* such kind of middleware queue can not be used for this scenario. It is populated with (nested) messages that are published to the message bus *while* handling a particular message. 

Imagine a scenario where X messages are published to the message bus which are totally isolated / not related to each other. Then only after handling all these X messages, some specific "shutdown" functionality should be invoked. Not in between the messages.

I think middleware can not be used to realize the intended functionality, therefore I considered using a shutdown function, or maybe the [destructor](http://php.net/manual/en/language.oop5.decon.php#language.oop5.decon.destructor) function...

**Comment by matthiasnoback** [comment]
I understand, but you could simply call that function after
https://github.com/SimpleBus/MessageBus/blob/master/src/Bus/Middleware/FinishesHandlingMessageBeforeHandlingNext.php#L42
right?
Otherwise, I wouldn't rely on `register_shutdown_function()` for important
work :) I'd just call the function/service explicitly then.

**Comment by holtkamp** [comment]
hehe, no, that "MiddleWare" approach as used in FinishesHandlingMessageBeforeHandlingNext won't help. 

As an example, when echoing at the position you suggested `'Finished handling Message'`, this:

```php
$eventBus->handle(new \Domain\Event(1));
echo 'Published Event 1 on EventBus';

$eventBus->handle(new \Domain\Event(2));
echo 'Published Event 2 on EventBus';

$eventBus->handle(new \Domain\Event(3));
echo 'Published Event 3 on EventBus';
```

would result in:
```
Finished handling Message
Published Event 1 on EventBus
Finished handling Message
Published Event 2 on EventBus
Finished handling Message
Published Event 3 on EventBus
```

While I am looking for:
```
Published Event 1 on EventBus
Published Event 2 on EventBus
Published Event 3 on EventBus
Finished handling all Messages: do additional stuff!
```

>I'd just call the function/service explicitly then.

The challenge is, the EventBus / CommandBus is a dependency that is injected all over the application. So nobody 'knows' when the last Event /Command is published on the EventBus / CommandBus. So it is also not possible to determine when to call the function explicitly, other than in a __destruct() or system shutdown function. I now went with the __destruct() approach, which seems to work fine. 


```php
class MessageBusSupportingMiddlewareAndDestructorFunction extends MessageBusSupportingMiddleware
{
    /**
     * @var int
     */
    private $numberOfHandledMessages = 0;

    /**
     * @var callable
     */
    private $shutdownFunction;

    /**
     * @var array
     */
    private $shutdownFunctionParameters;

    public function __construct(array $middlewares = [], callable $shutdownFunction, ...$shutdownFunctionParameters)
    {
        parent::__construct($middlewares);

        $this->shutdownFunction = $shutdownFunction;
        $this->shutdownFunctionParameters = $shutdownFunctionParameters;
    }

    public function handle($message): void
    {
        $this->numberOfHandledMessages++;

        parent::handle($message);
    }

    public function __destruct()
    {
        if ($this->numberOfHandledMessages > 0) {
            call_user_func_array($this->shutdownFunction, $this->shutdownFunctionParameters);
        }
    }
}
```

**Comment by matthiasnoback** [comment]
Okay, I understand. Still, I wouldn't rely on PHP's destruct/shutdown functionality, but make the call to the shutdown function explicitly (in particular if something important happens there). Also, with regard to code design, I wouldn't extend the existing class, but use object composition.

**Comment by holtkamp** [comment]
> I wouldn't rely on PHP's destruct/shutdown functionality, but make the call to the shutdown function explicitly

I agree, but having troubles wrapping my head around on where/when to invoke this function explicitly...

> I wouldn't extend the existing class, but use object composition.
Thanks, might be better indeed!

**Comment by matthiasnoback** [comment]
Okay :) Thanks for an interesting discussion.

**Comment by cmodijk** [comment]
@holtkamp / @matthiasnoback Thanks for the interesting discussion! What is the use case for something like this? If i look at our own implementation using a RabbitMQ the `__destruct` and `shutdown` will never happen only when we kill the command handlers. So I was wondering what you are trying to do. 

In our case we use symfony and if we want to do something at the end of a request ends so the user already gets the response it requested there is a `kernel.terminate` which we can use to listen on and do some work at the end of a request.
* https://github.com/symfony/symfony/blob/master/src/Symfony/Component/HttpKernel/HttpKernel.php#L84-L87
* https://github.com/symfony/symfony-standard/blob/3.3/web/app.php#L21

**Comment by holtkamp** [comment]
mmm, interesting. 

Our UseCase might be a bit exotic, but works quite nice now. It involves:

- a persistent / asynchronous EventBus
- [Bernard](http://bernard.readthedocs.io) to have the messages persisted on Amazon SQS queues (which [now supports FIFO](http://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues.html), nice for an EventBus where 'timing' is important)
- an application endpoint on our application that, when invoked, fetches Events from the EventBus and processes them (effectively: re-posts them on a synchronous EventBus 😄 )

**Challenge: reduce the time the Events are on the EventBus waiting to be processed**
The challenge is / was to inform a certain endpoint of events being posted on a Amazon SQS queue "as soon as possible", in a asynchronous way, but without having a separate process poll the queue to increase robustness (long-running processes might crash, etc, let there be chaos!).

A way would be to have a Amazon CloudWatch alarm fire as soon as messages are posted on the queue. The CloudWatch Alarm informs a Amazon SNS topic, which triggers a HTTP callback to the application endpoint that handles the Events persisted on the EventBus.

**Problem: Amazon SQS Metrics granularity**
Unfortunately the metrics of [Amazon SQS have a 5-minute granularity](http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/sqs-metricscollected.html). So the alarm could take 5 minutes to become active. Maybe this decreases in the future to 1 minute ("detailed monitoring"), or even less ("high resolution monitoring", but currently 5 minutes is what Amazon offers and that is too long. This would mean that after placing an Order, it might take up to 5 minutes before an e-mail is assembled and dispatched.

**Workaround: trigger alarm manually**
So the workaround for now is [to manually enable the CloudWatch Alarm](http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_SetAlarmState.html), so this is something we now do at the end of processing a request, when applicable (if any Events are submitted to the EventBus).

Maybe this approach sounds hacky, but it works nice and asynchronous. Additionally I expect the Amazon SQS metrics granularity to decrease in the (near?) future, so it is future proof. For [custom metrics such high resolution of 1 second is already available](https://aws.amazon.com/blogs/aws/new-high-resolution-custom-metrics-and-alarms-for-amazon-cloudwatch/). I guess it is only a matter of time before Amazon makes this available for their other services as well.

In case the `__destruct()` function is not invoked for whatever reason, the Amazon CloudWatch alarm will not be enabled by our code, but after 5 minutes when the metrics are processed. AFAIK this has not occurred yet, but would not be a disaster if it did happen...

**Comment by holtkamp** [comment]
FYI: after reading this blog post: https://tideways.io/profiler/blog/using-php-fpm-as-a-simple-built-in-async-queue, I decided to not manually enable a CloudWatch alarm, but use PHP-FPM to asynchronously inform a worker that Events were submitted to the EventBus. Works great.

Will try to come up with a PR for a `MessageBusSupportingMiddlewareAndDestructorFunction`

**Comment by cmodijk** [comment]
@holtkamp Thanks voor explaining this! It is a great read but as you stated it is a bit exotic. I'm looking forward for a PR for a `MessageBusSupportingMiddlewareAndDestructorFunction`.

**Comment by cmodijk** [comment]
I'm closing this as we have a PR for it know

**Comment by holtkamp** [comment]
@cmodijk since the PR was not merged https://github.com/SimpleBus/MessageBus/pull/75#issuecomment-353558762, would it be an option to re-open this issue and discuss other ways to realise the suggested functionality?
