### ISSUE TITLE
Mono repository

### ISSUE THREAD

**Issue by cmodijk** [SimpleBus/MessageBus#79]
At this time we have multiple packages within the `SimpleBus` organization and at times it is a pain to maintain. We are thinking on moving everything into a single mono repository and making read only subsplit packages.  

In this issue i want to track the progress and discues the pros and cons of going this route. 

The idea that i have at this point is that we should not release a composer package which contains everything but only use the mono repository for maintaining the  code base and use the splits to install specific parts. 

The only problem i see at this time is moving the old code base into one repo (which is not that hard to do) but then splitting them back into different repositories and preserving there history including tags which is the biggest challenge. If anyone have a clue how to do this or can help please let us know.

Possible solutions;
* http://scottwb.com/blog/2012/07/14/merge-git-repositories-and-preseve-commit-history/
* https://www.subtreesplit.com/

**Comment by theofidry** [comment]
👍  I'm for going back to a mono-repo. It's really my personal opinion but I do find it easier. I'll share an article shortly probably this weekend or next week) which could help on a few points like the framework integrations.

**Comment by nWidart** [comment]
For Asgardcms, I'm using something similar to subtreesplit.com, [but homemade by @julientant](https://github.com/AsgardCms/Subsplit/blob/golang/main.go).

This is in go, and is basically a rewrite of [dflydev/dflydev-git-subsplit-github-webhook](https://github.com/dflydev/dflydev-git-subsplit-github-webhook).

I didn't know about subtreesplit.com so if that works, that sounds nice.

However, on the first split, which [looks like this](https://github.com/Idavoll/Page/commit/572688def7119a49be54374cb199e7ff30da96c2), visible [on this page](https://github.com/Idavoll/Page/commits/3.0?after=6a9c48416d1a23fa0d80b172008507eba9bcdfe7+209) it made an 'initial commit' not preserving the history before that point. So that's a negative point.

Tags and branches, however, were split and maintained correctly on all splits.

Just my 2 cents. 👍

**Comment by cmodijk** [comment]
More references to other things
* https://www.youtube.com/watch?v=4w3-f6Xhvu8
* https://github.com/splitsh/lite

Source;
* https://twitter.com/matthiasnoback/status/936533692721311745

**Comment by EnchanterIO** [comment]
Regarding the Matthias status and the first part of the issue:

> "If you have some tips and tricks for merging repositories while preserving its history"

Once at work I did this (for every vendor I wanted to merge), to merge several repositories into one while preserving history: https://gist.github.com/EnchanterIO/29976a17d5ad26ebcfbb05c4eacb5073

Not sure if this is something you need but maybe it will help.

**Comment by fabpot** [comment]
I would of course recommend to use splitsh. It's been battle tested on the Symfony/Laravel/phpBB repositories for years now and it does not rely on the Git CLI (which means that it is at least two order of magnitude faster). Splitting the Symfony repository is basically real-time.

To merge all repositories, I would recommend something like tomono: https://github.com/unravelin/tomono (simple and efficient).

Send me an email if you'd like to get access to the hosted version, which makes things entirely automated.

**Comment by Nyholm** [comment]
Splitsh is far more advanced and feature rich than subtreesplit.com. No questions about it. 

But if you are okey with barley any features but a super simple 3-click setup SaaS, then subtreesplit.com might be the way to go. 

Like said before, all tags will still be in place and the contributors will be there. But the diff from latest (old) tag to master (after split) will not be possible. See https://github.com/geocoder-php/php-common/compare/v3.3.0...master

That repo is 5(?) years old. We introduced the subtreesplit this year.

**Comment by theofidry** [comment]
The article in question: [link](https://medium.com/@tfidry/managing-your-dependencies-in-php-321d584441ab)

**Comment by cafferata** [comment]
Thank you @theofidry for writing/sharing this! I have not thought about it before, interesting stuff. 👍

**Comment by cmodijk** [comment]
@fabpot I have send you a e-mail thanks for taking the time to help us out
@Nyholm I am still investigating our different options so also thanks for the help so far
@theofidry That is a great artikel! I think we should use these plugins to replace the methods for testing different versions against each other https://github.com/SimpleBus/SymfonyBridge/blob/master/.travis.yml#L26
@ruudk Thanks for helping me test these things in de background

To all other thanks for lending us your knowledge and help

**Comment by cmodijk** [comment]
Possible mapping of the repositories in the new mono repository

```
Root
├ Bridge
├─ DoctrineDBALBridge
├─ DoctrineORMBridge
├─ JMSSerializerBridge
├ Bundles
├─ AsynchronousBundle
├─ JMSSerializerBundleBridge
├─ RabbitMQBundleBridge
├─ SimpleBusBernardBundleBridge
├─ SymfonyBridge
├ Component
├─ Asynchronous
├─ MessageBus
├─ Serialization
````

A few notes about this 
* The `SymfonyBridge` is called a bridge but it contains bundles 
* There are multiple bundles in the `SymfonyBridge` repository should we separate them? Or combine the different other bundles into this? I think we should separate them

**Comment by theofidry** [comment]
Regarding your naming:

- I think you can drop the `Bridge` suffix, you already have it in the parent directory
- to me there is not difference between bundle and bridge, a bundle is just a Symfony bridge

So I would rather suggest something like:

```
src/
  Bridge/
    DoctrineDBAL/
    DoctrineORM/
    JSMSerializer/
    Symfony/
        AsynchronousBundle/
        JMSSerializerBundle/
        RabbitMQBundleBundle/
        SimpleBusBernardBundle/
  Asynchronous/
  MessageBus/
  Serialization/
```

I've been playing with this bridge approach a bit you can see an example on [this project](https://github.com/theofidry/AliceDataFixtures). The difference IMO in your case is that you have way more packages and for each of them you have several integrations. 

So maybe instead it would be better to rework the organisation per component:

```
src/
  
  Bridge/
    DoctrineDBAL/
    DoctrineORM/
    JSMSerializer/
    Symfony/
        AsynchronousBundle/
        JMSSerializerBundle/
        RabbitMQBundleBundle/
        SimpleBusBernardBundle/
  Asynchronous/
    ...
    Bridge/
      Symfony/ # content of the current AsynchronousBundle
  MessageBus/
    ...
    Bridge/
      DoctrineDBAL/
      DoctrineORM/
      Symfony/
      RabbitMQ/
      SimpleBusBernard/
  Serialization/
    ...
    Bridge/
      JSMSerializer/
      Symfony/
```

Note that the libraries I've linked and the mono repo with read-only splits are not incompatible. IMO you can leverage both. The libraries are linked can help a lot to provide a structure and ease proper testing whilst the read-only splits will ensure you still provide all the separate smaller packages you want.

**Comment by cmodijk** [comment]
@theofidry Thanks for the ideas we i think you have a good point in that bridges and bundles are just the same thing. The idea of separating them by component with the bridges is also very interesting. 

One other thing i tough about should we keep the docs in a separated repository? The docs are a mess at this point having most of them stil on the github.io domain but parts of it already in the new docs repository. I am curious about other people's opinions.

**Comment by cmodijk** [comment]
I also already created the repository for this it is empty for now https://github.com/SimpleBus/SimpleBus

**Comment by cmodijk** [comment]
Last Friday @ruudk and i merged all open pull requests en moved everything into the mono repository https://github.com/SimpleBus/SimpleBus. There is still a lot to do there but i'm closing this issue as it has happend. 

One side note; All new issues need to be opent on the mono repository al open issues are going to be closed as soon as possible.
